CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE TABLE "AppConfigEntries" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        key character varying(200) NOT NULL,
        value character varying(4000) NOT NULL,
        data_type character varying(20) NOT NULL,
        category character varying(50) NOT NULL,
        display_name character varying(200) NOT NULL,
        description character varying(500) NOT NULL,
        is_secret boolean NOT NULL,
        is_read_only boolean NOT NULL,
        requires_restart boolean NOT NULL,
        created_at timestamp without time zone NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        CONSTRAINT pk_app_config_entries PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE TABLE "NotificationTypes" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        description character varying(200),
        is_admin_controlled boolean NOT NULL,
        CONSTRAINT pk_notification_types PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE TABLE "Roles" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(50) NOT NULL,
        description character varying(200) NOT NULL,
        is_active boolean NOT NULL,
        created_at timestamp without time zone NOT NULL,
        CONSTRAINT pk_roles PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE TABLE "Users" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        email character varying(256) NOT NULL,
        first_name character varying(100) NOT NULL,
        last_name character varying(100) NOT NULL,
        password_hash character varying(255) NOT NULL,
        password_last_changed timestamp without time zone,
        role integer NOT NULL,
        created_at timestamp without time zone NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        is_active boolean NOT NULL,
        is_mfa_enabled boolean NOT NULL,
        mfa_secret character varying(255),
        mfa_enabled_at timestamp without time zone,
        backup_codes_json text NOT NULL,
        is_email_verified boolean NOT NULL,
        CONSTRAINT pk_users PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE TABLE "EmailVerificationTokens" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        token character varying(255) NOT NULL,
        created_at timestamp without time zone NOT NULL,
        expires_at timestamp without time zone NOT NULL,
        is_used boolean NOT NULL,
        used_at timestamp without time zone,
        user_id1 integer,
        CONSTRAINT pk_email_verification_tokens PRIMARY KEY (id),
        CONSTRAINT fk_email_verification_tokens_users_user_id FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE CASCADE,
        CONSTRAINT fk_email_verification_tokens_users_user_id1 FOREIGN KEY (user_id1) REFERENCES "Users" (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE TABLE "ExpenseCycles" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(150) NOT NULL,
        start_date timestamp without time zone NOT NULL,
        end_date timestamp without time zone NOT NULL,
        status integer NOT NULL,
        created_by_user_id integer NOT NULL,
        created_at timestamp without time zone NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        CONSTRAINT pk_expense_cycles PRIMARY KEY (id),
        CONSTRAINT fk_expense_cycles_users_created_by_user_id FOREIGN KEY (created_by_user_id) REFERENCES "Users" (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE TABLE "Notifications" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        user_id1 integer NOT NULL,
        message text NOT NULL,
        is_read boolean NOT NULL,
        is_archived boolean NOT NULL,
        created_at timestamp without time zone NOT NULL,
        type integer NOT NULL,
        deep_link_url text,
        related_entity_id integer,
        sent_via_push boolean NOT NULL,
        CONSTRAINT pk_notifications PRIMARY KEY (id),
        CONSTRAINT fk_notifications_users_user_id FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE CASCADE,
        CONSTRAINT fk_notifications_users_user_id1 FOREIGN KEY (user_id1) REFERENCES "Users" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE TABLE "PasswordResetTokens" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        token character varying(255) NOT NULL,
        created_at timestamp without time zone NOT NULL,
        expires_at timestamp without time zone NOT NULL,
        is_used boolean NOT NULL,
        used_at timestamp without time zone,
        user_id1 integer,
        CONSTRAINT pk_password_reset_tokens PRIMARY KEY (id),
        CONSTRAINT fk_password_reset_tokens_users_user_id FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE CASCADE,
        CONSTRAINT fk_password_reset_tokens_users_user_id1 FOREIGN KEY (user_id1) REFERENCES "Users" (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE TABLE "PushSubscriptions" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        user_id1 integer NOT NULL,
        endpoint text NOT NULL,
        p256dh text NOT NULL,
        auth text NOT NULL,
        user_agent text,
        created_at timestamp without time zone NOT NULL,
        CONSTRAINT pk_push_subscriptions PRIMARY KEY (id),
        CONSTRAINT fk_push_subscriptions_users_user_id FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE CASCADE,
        CONSTRAINT fk_push_subscriptions_users_user_id1 FOREIGN KEY (user_id1) REFERENCES "Users" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE TABLE "UserDevices" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        user_id1 integer NOT NULL,
        client_id text NOT NULL,
        device_type integer NOT NULL,
        device_model text,
        device_manufacturer text,
        os_version text,
        app_version text,
        user_agent text,
        friendly_name text,
        install_status integer NOT NULL,
        next_prompt_at timestamp without time zone,
        is_active boolean NOT NULL,
        last_seen_at timestamp without time zone NOT NULL,
        created_at timestamp without time zone NOT NULL,
        CONSTRAINT pk_user_devices PRIMARY KEY (id),
        CONSTRAINT fk_user_devices_users_user_id FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE CASCADE,
        CONSTRAINT fk_user_devices_users_user_id1 FOREIGN KEY (user_id1) REFERENCES "Users" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE TABLE "UserNotificationPreferences" (
        user_id integer NOT NULL,
        notification_type_id integer NOT NULL,
        is_enabled boolean NOT NULL,
        user_id1 integer NOT NULL,
        notification_type_id1 integer NOT NULL,
        CONSTRAINT pk_user_notification_preferences PRIMARY KEY (user_id, notification_type_id),
        CONSTRAINT fk_user_notification_preferences_notification_types_notification_ FOREIGN KEY (notification_type_id) REFERENCES "NotificationTypes" (id) ON DELETE CASCADE,
        CONSTRAINT "fk_user_notification_preferences_notification_types_notificati~" FOREIGN KEY (notification_type_id1) REFERENCES "NotificationTypes" (id) ON DELETE CASCADE,
        CONSTRAINT fk_user_notification_preferences_users_user_id FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE CASCADE,
        CONSTRAINT fk_user_notification_preferences_users_user_id1 FOREIGN KEY (user_id1) REFERENCES "Users" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE TABLE "CycleMembers" (
        expense_cycle_id integer NOT NULL,
        user_id integer NOT NULL,
        added_at timestamp without time zone NOT NULL,
        CONSTRAINT pk_cycle_members PRIMARY KEY (expense_cycle_id, user_id),
        CONSTRAINT fk_cycle_members_expense_cycles_expense_cycle_id FOREIGN KEY (expense_cycle_id) REFERENCES "ExpenseCycles" (id) ON DELETE CASCADE,
        CONSTRAINT fk_cycle_members_users_user_id FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE TABLE "Expenses" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        expense_cycle_id integer NOT NULL,
        title character varying(200) NOT NULL,
        amount numeric(18,2) NOT NULL,
        category integer NOT NULL,
        paid_by_user_id integer NOT NULL,
        notes character varying(500),
        created_at timestamp without time zone NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        CONSTRAINT pk_expenses PRIMARY KEY (id),
        CONSTRAINT fk_expenses_expense_cycles_expense_cycle_id FOREIGN KEY (expense_cycle_id) REFERENCES "ExpenseCycles" (id) ON DELETE CASCADE,
        CONSTRAINT fk_expenses_users_paid_by_user_id FOREIGN KEY (paid_by_user_id) REFERENCES "Users" (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE TABLE "Payments" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        payer_id integer NOT NULL,
        payee_id integer NOT NULL,
        expense_cycle_id integer NOT NULL,
        amount numeric(18,2) NOT NULL,
        status integer NOT NULL,
        notes character varying(500),
        created_at timestamp without time zone NOT NULL,
        confirmed_at timestamp without time zone,
        CONSTRAINT pk_payments PRIMARY KEY (id),
        CONSTRAINT fk_payments_expense_cycles_expense_cycle_id FOREIGN KEY (expense_cycle_id) REFERENCES "ExpenseCycles" (id) ON DELETE CASCADE,
        CONSTRAINT fk_payments_users_payee_id FOREIGN KEY (payee_id) REFERENCES "Users" (id) ON DELETE RESTRICT,
        CONSTRAINT fk_payments_users_payer_id FOREIGN KEY (payer_id) REFERENCES "Users" (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE TABLE "WebAuthnCredentials" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        credential_id character varying(512) NOT NULL,
        public_key text NOT NULL,
        sign_count bigint NOT NULL,
        aaguid character varying(100),
        device_friendly_name character varying(100),
        user_device_id integer,
        created_at timestamp without time zone NOT NULL,
        last_used_at timestamp without time zone,
        user_id1 integer NOT NULL,
        CONSTRAINT pk_web_authn_credentials PRIMARY KEY (id),
        CONSTRAINT fk_web_authn_credentials_user_devices_user_device_id FOREIGN KEY (user_device_id) REFERENCES "UserDevices" (id),
        CONSTRAINT fk_web_authn_credentials_users_user_id FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE CASCADE,
        CONSTRAINT fk_web_authn_credentials_users_user_id1 FOREIGN KEY (user_id1) REFERENCES "Users" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE TABLE "MemberObligations" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        expense_id integer NOT NULL,
        user_id integer NOT NULL,
        amount_owed numeric(18,2) NOT NULL,
        is_settled boolean NOT NULL,
        settled_at timestamp without time zone,
        created_at timestamp without time zone NOT NULL,
        CONSTRAINT pk_member_obligations PRIMARY KEY (id),
        CONSTRAINT fk_member_obligations_expenses_expense_id FOREIGN KEY (expense_id) REFERENCES "Expenses" (id) ON DELETE CASCADE,
        CONSTRAINT fk_member_obligations_users_user_id FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_app_config_entries_key ON "AppConfigEntries" (key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_cycle_members_user_id ON "CycleMembers" (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_email_verification_tokens_token ON "EmailVerificationTokens" (token);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_email_verification_tokens_user_id ON "EmailVerificationTokens" (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_email_verification_tokens_user_id1 ON "EmailVerificationTokens" (user_id1);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_expense_cycles_created_by_user_id ON "ExpenseCycles" (created_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_expenses_expense_cycle_id ON "Expenses" (expense_cycle_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_expenses_paid_by_user_id ON "Expenses" (paid_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_member_obligations_expense_id ON "MemberObligations" (expense_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_member_obligations_user_id ON "MemberObligations" (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_notifications_user_id ON "Notifications" (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_notifications_user_id1 ON "Notifications" (user_id1);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_password_reset_tokens_token ON "PasswordResetTokens" (token);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_password_reset_tokens_user_id ON "PasswordResetTokens" (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_password_reset_tokens_user_id1 ON "PasswordResetTokens" (user_id1);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_payments_expense_cycle_id ON "Payments" (expense_cycle_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_payments_payee_id ON "Payments" (payee_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_payments_payer_id ON "Payments" (payer_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_push_subscriptions_user_id ON "PushSubscriptions" (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_push_subscriptions_user_id1 ON "PushSubscriptions" (user_id1);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_roles_name ON "Roles" (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_user_devices_user_id ON "UserDevices" (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_user_devices_user_id1 ON "UserDevices" (user_id1);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_user_notification_preferences_notification_type_id ON "UserNotificationPreferences" (notification_type_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_user_notification_preferences_notification_type_id1 ON "UserNotificationPreferences" (notification_type_id1);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_user_notification_preferences_user_id1 ON "UserNotificationPreferences" (user_id1);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_users_email ON "Users" (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_web_authn_credentials_user_device_id ON "WebAuthnCredentials" (user_device_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_web_authn_credentials_user_id ON "WebAuthnCredentials" (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    CREATE INDEX ix_web_authn_credentials_user_id1 ON "WebAuthnCredentials" (user_id1);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402102500_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260402102500_InitialCreate', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402233736_FixUserNotificationPreferencesShadowColumns') THEN
    ALTER TABLE "UserNotificationPreferences" DROP CONSTRAINT "fk_user_notification_preferences_notification_types_notificati~";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402233736_FixUserNotificationPreferencesShadowColumns') THEN
    ALTER TABLE "UserNotificationPreferences" DROP CONSTRAINT fk_user_notification_preferences_users_user_id1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402233736_FixUserNotificationPreferencesShadowColumns') THEN
    DROP INDEX ix_user_notification_preferences_notification_type_id1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402233736_FixUserNotificationPreferencesShadowColumns') THEN
    DROP INDEX ix_user_notification_preferences_user_id1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402233736_FixUserNotificationPreferencesShadowColumns') THEN
    ALTER TABLE "UserNotificationPreferences" DROP COLUMN notification_type_id1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402233736_FixUserNotificationPreferencesShadowColumns') THEN
    ALTER TABLE "UserNotificationPreferences" DROP COLUMN user_id1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402233736_FixUserNotificationPreferencesShadowColumns') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260402233736_FixUserNotificationPreferencesShadowColumns', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402234605_FixShadowFkColumns') THEN
    ALTER TABLE "Notifications" DROP CONSTRAINT fk_notifications_users_user_id1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402234605_FixShadowFkColumns') THEN
    ALTER TABLE "PushSubscriptions" DROP CONSTRAINT fk_push_subscriptions_users_user_id1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402234605_FixShadowFkColumns') THEN
    ALTER TABLE "UserDevices" DROP CONSTRAINT fk_user_devices_users_user_id1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402234605_FixShadowFkColumns') THEN
    DROP INDEX ix_user_devices_user_id1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402234605_FixShadowFkColumns') THEN
    DROP INDEX ix_push_subscriptions_user_id1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402234605_FixShadowFkColumns') THEN
    DROP INDEX ix_notifications_user_id1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402234605_FixShadowFkColumns') THEN
    ALTER TABLE "UserDevices" DROP COLUMN user_id1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402234605_FixShadowFkColumns') THEN
    ALTER TABLE "PushSubscriptions" DROP COLUMN user_id1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402234605_FixShadowFkColumns') THEN
    ALTER TABLE "Notifications" DROP COLUMN user_id1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260402234605_FixShadowFkColumns') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260402234605_FixShadowFkColumns', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403042104_AddGroupsFeature') THEN
    ALTER TABLE "ExpenseCycles" ADD group_id integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403042104_AddGroupsFeature') THEN
    CREATE TABLE "Groups" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(150) NOT NULL,
        description character varying(500),
        is_active boolean NOT NULL,
        created_by_user_id integer NOT NULL,
        created_at timestamp without time zone NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        CONSTRAINT pk_groups PRIMARY KEY (id),
        CONSTRAINT fk_groups_users_created_by_user_id FOREIGN KEY (created_by_user_id) REFERENCES "Users" (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403042104_AddGroupsFeature') THEN
    CREATE TABLE "GroupMembers" (
        group_id integer NOT NULL,
        user_id integer NOT NULL,
        group_role integer NOT NULL,
        status integer NOT NULL,
        invited_by_user_id integer NOT NULL,
        invited_at timestamp without time zone NOT NULL,
        responded_at timestamp without time zone,
        CONSTRAINT pk_group_members PRIMARY KEY (group_id, user_id),
        CONSTRAINT fk_group_members_groups_group_id FOREIGN KEY (group_id) REFERENCES "Groups" (id) ON DELETE CASCADE,
        CONSTRAINT fk_group_members_users_invited_by_user_id FOREIGN KEY (invited_by_user_id) REFERENCES "Users" (id) ON DELETE RESTRICT,
        CONSTRAINT fk_group_members_users_user_id FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403042104_AddGroupsFeature') THEN
    CREATE INDEX ix_expense_cycles_group_id ON "ExpenseCycles" (group_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403042104_AddGroupsFeature') THEN
    CREATE INDEX ix_group_members_invited_by_user_id ON "GroupMembers" (invited_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403042104_AddGroupsFeature') THEN
    CREATE INDEX ix_group_members_user_id ON "GroupMembers" (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403042104_AddGroupsFeature') THEN
    CREATE INDEX ix_groups_created_by_user_id ON "Groups" (created_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403042104_AddGroupsFeature') THEN
    ALTER TABLE "ExpenseCycles" ADD CONSTRAINT fk_expense_cycles_groups_group_id FOREIGN KEY (group_id) REFERENCES "Groups" (id) ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403042104_AddGroupsFeature') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260403042104_AddGroupsFeature', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403044855_MakeGroupIdRequiredOnCycles') THEN
    ALTER TABLE "ExpenseCycles" DROP CONSTRAINT fk_expense_cycles_groups_group_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403044855_MakeGroupIdRequiredOnCycles') THEN
    UPDATE "ExpenseCycles" SET group_id = 0 WHERE group_id IS NULL;
    ALTER TABLE "ExpenseCycles" ALTER COLUMN group_id SET NOT NULL;
    ALTER TABLE "ExpenseCycles" ALTER COLUMN group_id SET DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403044855_MakeGroupIdRequiredOnCycles') THEN
    ALTER TABLE "ExpenseCycles" ADD CONSTRAINT fk_expense_cycles_groups_group_id FOREIGN KEY (group_id) REFERENCES "Groups" (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403044855_MakeGroupIdRequiredOnCycles') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260403044855_MakeGroupIdRequiredOnCycles', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403085439_CycleLifecycleAndDisputes') THEN
    ALTER TABLE "Expenses" DROP CONSTRAINT fk_expenses_users_paid_by_user_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403085439_CycleLifecycleAndDisputes') THEN
    ALTER TABLE "Expenses" RENAME COLUMN paid_by_user_id TO logged_by_user_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403085439_CycleLifecycleAndDisputes') THEN
    ALTER INDEX ix_expenses_paid_by_user_id RENAME TO ix_expenses_logged_by_user_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403085439_CycleLifecycleAndDisputes') THEN
    ALTER TABLE "ExpenseCycles" ADD closing_soon_sent boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403085439_CycleLifecycleAndDisputes') THEN
    ALTER TABLE "ExpenseCycles" ADD mid_reminder_sent boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403085439_CycleLifecycleAndDisputes') THEN
    ALTER TABLE "ExpenseCycles" ADD split_type integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403085439_CycleLifecycleAndDisputes') THEN
    ALTER TABLE "ExpenseCycles" ADD start_notification_sent boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403085439_CycleLifecycleAndDisputes') THEN
    ALTER TABLE "CycleMembers" ADD share_percentage numeric;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403085439_CycleLifecycleAndDisputes') THEN
    CREATE TABLE "ExpenseDisputes" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        expense_id integer NOT NULL,
        raised_by_user_id integer NOT NULL,
        reason character varying(1000) NOT NULL,
        status integer NOT NULL,
        admin_notes character varying(1000),
        created_at timestamp without time zone NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        CONSTRAINT pk_expense_disputes PRIMARY KEY (id),
        CONSTRAINT fk_expense_disputes_expenses_expense_id FOREIGN KEY (expense_id) REFERENCES "Expenses" (id) ON DELETE CASCADE,
        CONSTRAINT fk_expense_disputes_users_raised_by_user_id FOREIGN KEY (raised_by_user_id) REFERENCES "Users" (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403085439_CycleLifecycleAndDisputes') THEN
    CREATE INDEX ix_expense_disputes_expense_id ON "ExpenseDisputes" (expense_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403085439_CycleLifecycleAndDisputes') THEN
    CREATE INDEX ix_expense_disputes_raised_by_user_id ON "ExpenseDisputes" (raised_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403085439_CycleLifecycleAndDisputes') THEN
    ALTER TABLE "Expenses" ADD CONSTRAINT fk_expenses_users_logged_by_user_id FOREIGN KEY (logged_by_user_id) REFERENCES "Users" (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260403085439_CycleLifecycleAndDisputes') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260403085439_CycleLifecycleAndDisputes', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260404044121_FixEmailVerificationTokenUserNavigation') THEN
    ALTER TABLE "EmailVerificationTokens" DROP CONSTRAINT fk_email_verification_tokens_users_user_id1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260404044121_FixEmailVerificationTokenUserNavigation') THEN
    DROP INDEX ix_email_verification_tokens_user_id1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260404044121_FixEmailVerificationTokenUserNavigation') THEN
    ALTER TABLE "EmailVerificationTokens" DROP COLUMN user_id1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260404044121_FixEmailVerificationTokenUserNavigation') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260404044121_FixEmailVerificationTokenUserNavigation', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260404111949_FeedbackManagement') THEN
    CREATE TABLE "FeatureBugReports" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        title character varying(200) NOT NULL,
        description character varying(2000) NOT NULL,
        type integer NOT NULL,
        priority integer NOT NULL,
        status integer NOT NULL,
        version_number character varying(20),
        submitted_by_user_id integer NOT NULL,
        created_at timestamp without time zone NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        CONSTRAINT pk_feature_bug_reports PRIMARY KEY (id),
        CONSTRAINT fk_feature_bug_reports_users_submitted_by_user_id FOREIGN KEY (submitted_by_user_id) REFERENCES "Users" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260404111949_FeedbackManagement') THEN
    CREATE TABLE "FeatureBugReportCategories" (
        feature_bug_report_id integer NOT NULL,
        category integer NOT NULL,
        CONSTRAINT pk_feature_bug_report_categories PRIMARY KEY (feature_bug_report_id, category),
        CONSTRAINT fk_feature_bug_report_categories_feature_bug_reports_feature_bug_re FOREIGN KEY (feature_bug_report_id) REFERENCES "FeatureBugReports" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260404111949_FeedbackManagement') THEN
    CREATE INDEX ix_feature_bug_reports_submitted_by_user_id ON "FeatureBugReports" (submitted_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260404111949_FeedbackManagement') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260404111949_FeedbackManagement', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    ALTER TABLE "ExpenseCycles" ADD contribution_amount numeric(18,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    ALTER TABLE "ExpenseCycles" ADD currency_id integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    ALTER TABLE "ExpenseCycles" ADD cycle_type integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    ALTER TABLE "ExpenseCycles" ADD frequency integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE TABLE "Currencies" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        code character varying(3) NOT NULL,
        name character varying(50) NOT NULL,
        symbol character varying(5) NOT NULL,
        is_active boolean NOT NULL,
        CONSTRAINT pk_currencies PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE TABLE "MukandoOptOutRequests" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        expense_cycle_id integer NOT NULL,
        user_id integer NOT NULL,
        reason character varying(500) NOT NULL,
        status integer NOT NULL,
        responded_by_user_id integer,
        created_at timestamp without time zone NOT NULL,
        responded_at timestamp without time zone,
        CONSTRAINT pk_mukando_opt_out_requests PRIMARY KEY (id),
        CONSTRAINT fk_mukando_opt_out_requests_expense_cycles_expense_cycle_id FOREIGN KEY (expense_cycle_id) REFERENCES "ExpenseCycles" (id) ON DELETE CASCADE,
        CONSTRAINT fk_mukando_opt_out_requests_users_responded_by_user_id FOREIGN KEY (responded_by_user_id) REFERENCES "Users" (id) ON DELETE RESTRICT,
        CONSTRAINT fk_mukando_opt_out_requests_users_user_id FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE TABLE "MukandoRounds" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        expense_cycle_id integer NOT NULL,
        round_number integer NOT NULL,
        recipient_user_id integer NOT NULL,
        status integer NOT NULL,
        expected_pool numeric(18,2) NOT NULL,
        actual_collected numeric(18,2) NOT NULL,
        payout_confirmed boolean NOT NULL,
        payout_confirmed_at timestamp without time zone,
        due_date timestamp without time zone NOT NULL,
        created_at timestamp without time zone NOT NULL,
        updated_at timestamp without time zone NOT NULL,
        CONSTRAINT pk_mukando_rounds PRIMARY KEY (id),
        CONSTRAINT fk_mukando_rounds_expense_cycles_expense_cycle_id FOREIGN KEY (expense_cycle_id) REFERENCES "ExpenseCycles" (id) ON DELETE CASCADE,
        CONSTRAINT fk_mukando_rounds_users_recipient_user_id FOREIGN KEY (recipient_user_id) REFERENCES "Users" (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE TABLE "MukandoContributions" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        mukando_round_id integer NOT NULL,
        user_id integer NOT NULL,
        amount numeric(18,2) NOT NULL,
        status integer NOT NULL,
        proof_url character varying(500),
        reference character varying(200),
        paid_at timestamp without time zone,
        confirmed_by_admin_at timestamp without time zone,
        notes character varying(500),
        reminder1sent boolean NOT NULL,
        reminder2sent boolean NOT NULL,
        escalation_sent boolean NOT NULL,
        created_at timestamp without time zone NOT NULL,
        CONSTRAINT pk_mukando_contributions PRIMARY KEY (id),
        CONSTRAINT fk_mukando_contributions_mukando_rounds_mukando_round_id FOREIGN KEY (mukando_round_id) REFERENCES "MukandoRounds" (id) ON DELETE CASCADE,
        CONSTRAINT fk_mukando_contributions_users_user_id FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE TABLE "MukandoPayouts" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        mukando_round_id integer NOT NULL,
        recipient_user_id integer NOT NULL,
        amount_disbursed numeric(18,2) NOT NULL,
        payment_method integer NOT NULL,
        proof_url character varying(500) NOT NULL,
        reference character varying(200),
        confirmed_by_user_id integer NOT NULL,
        created_at timestamp without time zone NOT NULL,
        CONSTRAINT pk_mukando_payouts PRIMARY KEY (id),
        CONSTRAINT fk_mukando_payouts_mukando_rounds_mukando_round_id FOREIGN KEY (mukando_round_id) REFERENCES "MukandoRounds" (id) ON DELETE CASCADE,
        CONSTRAINT fk_mukando_payouts_users_confirmed_by_user_id FOREIGN KEY (confirmed_by_user_id) REFERENCES "Users" (id) ON DELETE RESTRICT,
        CONSTRAINT fk_mukando_payouts_users_recipient_user_id FOREIGN KEY (recipient_user_id) REFERENCES "Users" (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE TABLE "MukandoRoundActivities" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        mukando_round_id integer NOT NULL,
        user_id integer NOT NULL,
        action integer NOT NULL,
        details character varying(500) NOT NULL,
        created_at timestamp without time zone NOT NULL,
        CONSTRAINT pk_mukando_round_activities PRIMARY KEY (id),
        CONSTRAINT fk_mukando_round_activities_mukando_rounds_mukando_round_id FOREIGN KEY (mukando_round_id) REFERENCES "MukandoRounds" (id) ON DELETE CASCADE,
        CONSTRAINT fk_mukando_round_activities_users_user_id FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE TABLE "MukandoSwapRequests" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        expense_cycle_id integer NOT NULL,
        requester_user_id integer NOT NULL,
        requester_round_id integer NOT NULL,
        target_user_id integer NOT NULL,
        target_round_id integer NOT NULL,
        status integer NOT NULL,
        created_at timestamp without time zone NOT NULL,
        responded_at timestamp without time zone,
        CONSTRAINT pk_mukando_swap_requests PRIMARY KEY (id),
        CONSTRAINT fk_mukando_swap_requests_expense_cycles_expense_cycle_id FOREIGN KEY (expense_cycle_id) REFERENCES "ExpenseCycles" (id) ON DELETE CASCADE,
        CONSTRAINT fk_mukando_swap_requests_mukando_rounds_requester_round_id FOREIGN KEY (requester_round_id) REFERENCES "MukandoRounds" (id) ON DELETE RESTRICT,
        CONSTRAINT fk_mukando_swap_requests_mukando_rounds_target_round_id FOREIGN KEY (target_round_id) REFERENCES "MukandoRounds" (id) ON DELETE RESTRICT,
        CONSTRAINT fk_mukando_swap_requests_users_requester_user_id FOREIGN KEY (requester_user_id) REFERENCES "Users" (id) ON DELETE RESTRICT,
        CONSTRAINT fk_mukando_swap_requests_users_target_user_id FOREIGN KEY (target_user_id) REFERENCES "Users" (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE INDEX ix_expense_cycles_currency_id ON "ExpenseCycles" (currency_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE UNIQUE INDEX ix_currencies_code ON "Currencies" (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN

                    INSERT INTO "Currencies" (code, name, symbol, is_active)
                    VALUES ('USD', 'US Dollar', '$', true);
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN

                    UPDATE "ExpenseCycles" SET currency_id = (SELECT id FROM "Currencies" WHERE code = 'USD' LIMIT 1);
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE UNIQUE INDEX ix_mukando_contributions_mukando_round_id_user_id ON "MukandoContributions" (mukando_round_id, user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE INDEX ix_mukando_contributions_user_id ON "MukandoContributions" (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE INDEX ix_mukando_opt_out_requests_expense_cycle_id ON "MukandoOptOutRequests" (expense_cycle_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE INDEX ix_mukando_opt_out_requests_responded_by_user_id ON "MukandoOptOutRequests" (responded_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE INDEX ix_mukando_opt_out_requests_user_id ON "MukandoOptOutRequests" (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE INDEX ix_mukando_payouts_confirmed_by_user_id ON "MukandoPayouts" (confirmed_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE UNIQUE INDEX ix_mukando_payouts_mukando_round_id ON "MukandoPayouts" (mukando_round_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE INDEX ix_mukando_payouts_recipient_user_id ON "MukandoPayouts" (recipient_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE INDEX ix_mukando_round_activities_mukando_round_id ON "MukandoRoundActivities" (mukando_round_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE INDEX ix_mukando_round_activities_user_id ON "MukandoRoundActivities" (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE UNIQUE INDEX ix_mukando_rounds_expense_cycle_id_round_number ON "MukandoRounds" (expense_cycle_id, round_number);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE INDEX ix_mukando_rounds_recipient_user_id ON "MukandoRounds" (recipient_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE INDEX ix_mukando_swap_requests_expense_cycle_id ON "MukandoSwapRequests" (expense_cycle_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE INDEX ix_mukando_swap_requests_requester_round_id ON "MukandoSwapRequests" (requester_round_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE INDEX ix_mukando_swap_requests_requester_user_id ON "MukandoSwapRequests" (requester_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE INDEX ix_mukando_swap_requests_target_round_id ON "MukandoSwapRequests" (target_round_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    CREATE INDEX ix_mukando_swap_requests_target_user_id ON "MukandoSwapRequests" (target_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    ALTER TABLE "ExpenseCycles" ADD CONSTRAINT fk_expense_cycles_currencies_currency_id FOREIGN KEY (currency_id) REFERENCES "Currencies" (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405003005_AddMukandoCycleType') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260405003005_AddMukandoCycleType', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405033542_AddGroupJoinCodes') THEN
    ALTER TABLE "Groups" ADD join_code character varying(8) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405033542_AddGroupJoinCodes') THEN
    ALTER TABLE "Groups" ADD join_code_generated_at timestamp without time zone NOT NULL DEFAULT TIMESTAMP '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405033542_AddGroupJoinCodes') THEN

                    UPDATE "Groups"
                    SET join_code = UPPER(SUBSTRING(MD5(RANDOM()::text || id::text) FROM 1 FOR 8)),
                        join_code_generated_at = NOW() AT TIME ZONE 'UTC'
                    WHERE join_code = '';
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405033542_AddGroupJoinCodes') THEN
    ALTER TABLE "GroupMembers" ALTER COLUMN invited_by_user_id DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405033542_AddGroupJoinCodes') THEN
    ALTER TABLE "GroupMembers" ADD approved_at timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405033542_AddGroupJoinCodes') THEN
    ALTER TABLE "GroupMembers" ADD approved_by_user_id integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405033542_AddGroupJoinCodes') THEN
    ALTER TABLE "GroupMembers" ADD join_requested_at timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405033542_AddGroupJoinCodes') THEN
    CREATE UNIQUE INDEX ix_groups_join_code ON "Groups" (join_code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405033542_AddGroupJoinCodes') THEN
    CREATE INDEX ix_group_members_approved_by_user_id ON "GroupMembers" (approved_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405033542_AddGroupJoinCodes') THEN
    ALTER TABLE "GroupMembers" ADD CONSTRAINT fk_group_members_users_approved_by_user_id FOREIGN KEY (approved_by_user_id) REFERENCES "Users" (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405033542_AddGroupJoinCodes') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260405033542_AddGroupJoinCodes', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405070344_AddUploadedFiles') THEN
    CREATE TABLE uploaded_files (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        file_name character varying(255) NOT NULL,
        content_type character varying(100) NOT NULL,
        data bytea NOT NULL,
        size_bytes bigint NOT NULL,
        folder character varying(50) NOT NULL,
        uploaded_at timestamp without time zone NOT NULL,
        uploaded_by_user_id integer NOT NULL,
        uploaded_by_id integer,
        CONSTRAINT pk_uploaded_files PRIMARY KEY (id),
        CONSTRAINT fk_uploaded_files_users_uploaded_by_id FOREIGN KEY (uploaded_by_id) REFERENCES "Users" (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405070344_AddUploadedFiles') THEN
    CREATE INDEX ix_uploaded_files_uploaded_by_id ON uploaded_files (uploaded_by_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260405070344_AddUploadedFiles') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260405070344_AddUploadedFiles', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260406032721_AddImageToFeatureBugReport') THEN
    ALTER TABLE "FeatureBugReports" ADD image_file_id integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260406032721_AddImageToFeatureBugReport') THEN
    CREATE INDEX ix_feature_bug_reports_image_file_id ON "FeatureBugReports" (image_file_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260406032721_AddImageToFeatureBugReport') THEN
    ALTER TABLE "FeatureBugReports" ADD CONSTRAINT fk_feature_bug_reports_uploaded_files_image_file_id FOREIGN KEY (image_file_id) REFERENCES uploaded_files (id) ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260406032721_AddImageToFeatureBugReport') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260406032721_AddImageToFeatureBugReport', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260406063430_RenameMukandoOptOutsToCycleOptOuts') THEN
    ALTER TABLE "MukandoOptOutRequests" RENAME TO "CycleOptOutRequests";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260406063430_RenameMukandoOptOutsToCycleOptOuts') THEN
    ALTER INDEX ix_mukando_opt_out_requests_expense_cycle_id RENAME TO ix_cycle_opt_out_requests_expense_cycle_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260406063430_RenameMukandoOptOutsToCycleOptOuts') THEN
    ALTER INDEX ix_mukando_opt_out_requests_responded_by_user_id RENAME TO ix_cycle_opt_out_requests_responded_by_user_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260406063430_RenameMukandoOptOutsToCycleOptOuts') THEN
    ALTER INDEX ix_mukando_opt_out_requests_user_id RENAME TO ix_cycle_opt_out_requests_user_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260406063430_RenameMukandoOptOutsToCycleOptOuts') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260406063430_RenameMukandoOptOutsToCycleOptOuts', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260406065127_AddTourCompletedAt') THEN
    ALTER TABLE "Users" ADD tour_completed_at timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260406065127_AddTourCompletedAt') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260406065127_AddTourCompletedAt', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410064454_AddMukandoVerificationRequests') THEN
    CREATE TABLE "MukandoVerificationRequests" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        mukando_round_id integer NOT NULL,
        target integer NOT NULL,
        mukando_contribution_id integer,
        pending_payout_amount numeric(18,2),
        pending_payout_method integer,
        pending_payout_proof_url character varying(500),
        pending_payout_reference character varying(200),
        initiated_by_user_id integer NOT NULL,
        assigned_to_user_id integer NOT NULL,
        status integer NOT NULL,
        rejection_reason character varying(500),
        responded_by_user_id integer,
        responded_at timestamp without time zone,
        expires_at timestamp without time zone NOT NULL,
        created_at timestamp without time zone NOT NULL,
        CONSTRAINT pk_mukando_verification_requests PRIMARY KEY (id),
        CONSTRAINT fk_mukando_verification_requests_mukando_rounds_mukando_round_id FOREIGN KEY (mukando_round_id) REFERENCES "MukandoRounds" (id) ON DELETE CASCADE,
        CONSTRAINT fk_mukando_verification_requests_users_assigned_to_user_id FOREIGN KEY (assigned_to_user_id) REFERENCES "Users" (id) ON DELETE RESTRICT,
        CONSTRAINT fk_mukando_verification_requests_users_initiated_by_user_id FOREIGN KEY (initiated_by_user_id) REFERENCES "Users" (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410064454_AddMukandoVerificationRequests') THEN
    CREATE INDEX ix_mukando_verification_requests_assigned_to_user_id ON "MukandoVerificationRequests" (assigned_to_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410064454_AddMukandoVerificationRequests') THEN
    CREATE INDEX ix_mukando_verification_requests_initiated_by_user_id ON "MukandoVerificationRequests" (initiated_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410064454_AddMukandoVerificationRequests') THEN
    CREATE INDEX ix_mukando_verification_requests_mukando_round_id ON "MukandoVerificationRequests" (mukando_round_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410064454_AddMukandoVerificationRequests') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260410064454_AddMukandoVerificationRequests', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410073003_AddSentEmailsAndBccConfig') THEN
    CREATE TABLE sent_emails (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        to_address character varying(255) NOT NULL,
        subject character varying(500) NOT NULL,
        html_body text NOT NULL,
        plain_body text,
        bcc_address character varying(255),
        sent_at timestamp without time zone NOT NULL,
        is_success boolean NOT NULL,
        error_message text,
        CONSTRAINT pk_sent_emails PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410073003_AddSentEmailsAndBccConfig') THEN
    CREATE INDEX "IX_sent_emails_sent_at" ON sent_emails (sent_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410073003_AddSentEmailsAndBccConfig') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260410073003_AddSentEmailsAndBccConfig', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410084512_AddCycleMemberAgreements') THEN
    CREATE TABLE "CycleMemberAgreements" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        expense_cycle_id integer NOT NULL,
        user_id integer NOT NULL,
        agreed_at timestamp without time zone NOT NULL,
        CONSTRAINT pk_cycle_member_agreements PRIMARY KEY (id),
        CONSTRAINT fk_cycle_member_agreements_expense_cycles_expense_cycle_id FOREIGN KEY (expense_cycle_id) REFERENCES "ExpenseCycles" (id) ON DELETE CASCADE,
        CONSTRAINT fk_cycle_member_agreements_users_user_id FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410084512_AddCycleMemberAgreements') THEN
    CREATE UNIQUE INDEX ix_cycle_member_agreements_expense_cycle_id_user_id ON "CycleMemberAgreements" (expense_cycle_id, user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410084512_AddCycleMemberAgreements') THEN
    CREATE INDEX ix_cycle_member_agreements_user_id ON "CycleMemberAgreements" (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410084512_AddCycleMemberAgreements') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260410084512_AddCycleMemberAgreements', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410093437_AddKycVerification') THEN
    ALTER TABLE "Users" ADD kyc_status integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410093437_AddKycVerification') THEN
    ALTER TABLE "Users" ADD phone_number character varying(30);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410093437_AddKycVerification') THEN
    CREATE TABLE "UserKycDocuments" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        id_type integer NOT NULL,
        id_number character varying(100),
        full_name_on_id character varying(200) NOT NULL,
        document_file_id integer,
        selfie_with_id_file_id integer,
        status integer NOT NULL,
        submitted_at timestamp without time zone NOT NULL,
        reviewed_by_user_id integer,
        reviewed_at timestamp without time zone,
        rejection_reason character varying(500),
        admin_bypass_note character varying(500),
        CONSTRAINT pk_user_kyc_documents PRIMARY KEY (id),
        CONSTRAINT fk_user_kyc_documents_uploaded_files_document_file_id FOREIGN KEY (document_file_id) REFERENCES uploaded_files (id) ON DELETE SET NULL,
        CONSTRAINT fk_user_kyc_documents_uploaded_files_selfie_with_id_file_id FOREIGN KEY (selfie_with_id_file_id) REFERENCES uploaded_files (id) ON DELETE SET NULL,
        CONSTRAINT fk_user_kyc_documents_users_reviewed_by_user_id FOREIGN KEY (reviewed_by_user_id) REFERENCES "Users" (id) ON DELETE SET NULL,
        CONSTRAINT fk_user_kyc_documents_users_user_id FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410093437_AddKycVerification') THEN
    CREATE INDEX ix_user_kyc_documents_document_file_id ON "UserKycDocuments" (document_file_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410093437_AddKycVerification') THEN
    CREATE INDEX ix_user_kyc_documents_reviewed_by_user_id ON "UserKycDocuments" (reviewed_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410093437_AddKycVerification') THEN
    CREATE INDEX ix_user_kyc_documents_selfie_with_id_file_id ON "UserKycDocuments" (selfie_with_id_file_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410093437_AddKycVerification') THEN
    CREATE INDEX "IX_UserKycDocuments_Status" ON "UserKycDocuments" (status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410093437_AddKycVerification') THEN
    CREATE INDEX "IX_UserKycDocuments_UserId" ON "UserKycDocuments" (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410093437_AddKycVerification') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260410093437_AddKycVerification', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410111301_AddReminderJobs') THEN
    CREATE TABLE "ReminderJobs" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        notification_type integer NOT NULL,
        subject_type character varying(50) NOT NULL,
        subject_id integer NOT NULL,
        stage_key character varying(50) NOT NULL,
        idempotency_key character varying(200) NOT NULL,
        scheduled_for_utc timestamp without time zone NOT NULL,
        status integer NOT NULL,
        title character varying(200) NOT NULL,
        body character varying(1000) NOT NULL,
        deep_link_url character varying(500),
        related_entity_id integer,
        sent_at_utc timestamp without time zone,
        cancelled_at_utc timestamp without time zone,
        retry_count integer NOT NULL,
        last_error character varying(1000),
        created_at_utc timestamp without time zone NOT NULL,
        CONSTRAINT pk_reminder_jobs PRIMARY KEY (id),
        CONSTRAINT fk_reminder_jobs_users_user_id FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410111301_AddReminderJobs') THEN
    CREATE UNIQUE INDEX ix_reminder_jobs_idempotency_key ON "ReminderJobs" (idempotency_key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410111301_AddReminderJobs') THEN
    CREATE INDEX ix_reminder_jobs_user_id ON "ReminderJobs" (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410111301_AddReminderJobs') THEN
    CREATE INDEX "IX_ReminderJobs_Status_ScheduledForUtc" ON "ReminderJobs" (status, scheduled_for_utc);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410111301_AddReminderJobs') THEN
    CREATE INDEX "IX_ReminderJobs_Subject_Status" ON "ReminderJobs" (subject_type, subject_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260410111301_AddReminderJobs') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260410111301_AddReminderJobs', '10.0.3');
    END IF;
END $EF$;
COMMIT;

