// <auto-generated />
using System;
using Batanai.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Batanai.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260405033542_AddGroupJoinCodes")]
    partial class AddGroupJoinCodes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Batanai.Api.Models.AppConfigEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("data_type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read_only");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean")
                        .HasColumnName("is_secret");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<bool>("RequiresRestart")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_restart");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_app_config_entries");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_app_config_entries_key");

                    b.ToTable("AppConfigEntries", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_currencies");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_currencies_code");

                    b.ToTable("Currencies", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.CycleMember", b =>
                {
                    b.Property<int>("ExpenseCycleId")
                        .HasColumnType("integer")
                        .HasColumnName("expense_cycle_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_at");

                    b.Property<decimal?>("SharePercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("share_percentage");

                    b.HasKey("ExpenseCycleId", "UserId")
                        .HasName("pk_cycle_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_cycle_members_user_id");

                    b.ToTable("CycleMembers", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.EmailVerificationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("used_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_email_verification_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_email_verification_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_email_verification_tokens_user_id");

                    b.ToTable("EmailVerificationTokens", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpenseCycleId")
                        .HasColumnType("integer")
                        .HasColumnName("expense_cycle_id");

                    b.Property<int>("LoggedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("logged_by_user_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_expenses");

                    b.HasIndex("ExpenseCycleId")
                        .HasDatabaseName("ix_expenses_expense_cycle_id");

                    b.HasIndex("LoggedByUserId")
                        .HasDatabaseName("ix_expenses_logged_by_user_id");

                    b.ToTable("Expenses", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.ExpenseCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ClosingSoonSent")
                        .HasColumnType("boolean")
                        .HasColumnName("closing_soon_sent");

                    b.Property<decimal?>("ContributionAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("contribution_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_id");

                    b.Property<int>("CycleType")
                        .HasColumnType("integer")
                        .HasColumnName("cycle_type");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<int?>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<bool>("MidReminderSent")
                        .HasColumnType("boolean")
                        .HasColumnName("mid_reminder_sent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SplitType")
                        .HasColumnType("integer")
                        .HasColumnName("split_type");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<bool>("StartNotificationSent")
                        .HasColumnType("boolean")
                        .HasColumnName("start_notification_sent");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_expense_cycles");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_expense_cycles_created_by_user_id");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_expense_cycles_currency_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_expense_cycles_group_id");

                    b.ToTable("ExpenseCycles", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.ExpenseDispute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("admin_notes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpenseId")
                        .HasColumnType("integer")
                        .HasColumnName("expense_id");

                    b.Property<int>("RaisedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("raised_by_user_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_expense_disputes");

                    b.HasIndex("ExpenseId")
                        .HasDatabaseName("ix_expense_disputes_expense_id");

                    b.HasIndex("RaisedByUserId")
                        .HasDatabaseName("ix_expense_disputes_raised_by_user_id");

                    b.ToTable("ExpenseDisputes", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.FeatureBugReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("SubmittedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("submitted_by_user_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VersionNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_feature_bug_reports");

                    b.HasIndex("SubmittedByUserId")
                        .HasDatabaseName("ix_feature_bug_reports_submitted_by_user_id");

                    b.ToTable("FeatureBugReports", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.FeatureBugReportCategory", b =>
                {
                    b.Property<int>("FeatureBugReportId")
                        .HasColumnType("integer")
                        .HasColumnName("feature_bug_report_id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.HasKey("FeatureBugReportId", "Category")
                        .HasName("pk_feature_bug_report_categories");

                    b.ToTable("FeatureBugReportCategories", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("join_code");

                    b.Property<DateTime>("JoinCodeGeneratedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("join_code_generated_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_groups_created_by_user_id");

                    b.HasIndex("JoinCode")
                        .IsUnique()
                        .HasDatabaseName("ix_groups_join_code");

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.GroupMember", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by_user_id");

                    b.Property<int>("GroupRole")
                        .HasColumnType("integer")
                        .HasColumnName("group_role");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("invited_at");

                    b.Property<int?>("InvitedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("invited_by_user_id");

                    b.Property<DateTime?>("JoinRequestedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("join_requested_at");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("responded_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("GroupId", "UserId")
                        .HasName("pk_group_members");

                    b.HasIndex("ApprovedByUserId")
                        .HasDatabaseName("ix_group_members_approved_by_user_id");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("ix_group_members_invited_by_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_group_members_user_id");

                    b.ToTable("GroupMembers", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.MemberObligation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountOwed")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_owed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpenseId")
                        .HasColumnType("integer")
                        .HasColumnName("expense_id");

                    b.Property<bool>("IsSettled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_settled");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("settled_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_member_obligations");

                    b.HasIndex("ExpenseId")
                        .HasDatabaseName("ix_member_obligations_expense_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_member_obligations_user_id");

                    b.ToTable("MemberObligations", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.MukandoContribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("ConfirmedByAdminAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("confirmed_by_admin_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("EscalationSent")
                        .HasColumnType("boolean")
                        .HasColumnName("escalation_sent");

                    b.Property<int>("MukandoRoundId")
                        .HasColumnType("integer")
                        .HasColumnName("mukando_round_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("ProofUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("proof_url");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference");

                    b.Property<bool>("Reminder1Sent")
                        .HasColumnType("boolean")
                        .HasColumnName("reminder1sent");

                    b.Property<bool>("Reminder2Sent")
                        .HasColumnType("boolean")
                        .HasColumnName("reminder2sent");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_mukando_contributions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mukando_contributions_user_id");

                    b.HasIndex("MukandoRoundId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_mukando_contributions_mukando_round_id_user_id");

                    b.ToTable("MukandoContributions", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.MukandoOptOutRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpenseCycleId")
                        .HasColumnType("integer")
                        .HasColumnName("expense_cycle_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("responded_at");

                    b.Property<int?>("RespondedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("responded_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_mukando_opt_out_requests");

                    b.HasIndex("ExpenseCycleId")
                        .HasDatabaseName("ix_mukando_opt_out_requests_expense_cycle_id");

                    b.HasIndex("RespondedByUserId")
                        .HasDatabaseName("ix_mukando_opt_out_requests_responded_by_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mukando_opt_out_requests_user_id");

                    b.ToTable("MukandoOptOutRequests", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.MukandoPayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountDisbursed")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_disbursed");

                    b.Property<int>("ConfirmedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("confirmed_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MukandoRoundId")
                        .HasColumnType("integer")
                        .HasColumnName("mukando_round_id");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method");

                    b.Property<string>("ProofUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("proof_url");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_user_id");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference");

                    b.HasKey("Id")
                        .HasName("pk_mukando_payouts");

                    b.HasIndex("ConfirmedByUserId")
                        .HasDatabaseName("ix_mukando_payouts_confirmed_by_user_id");

                    b.HasIndex("MukandoRoundId")
                        .IsUnique()
                        .HasDatabaseName("ix_mukando_payouts_mukando_round_id");

                    b.HasIndex("RecipientUserId")
                        .HasDatabaseName("ix_mukando_payouts_recipient_user_id");

                    b.ToTable("MukandoPayouts", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.MukandoRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualCollected")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("actual_collected");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("due_date");

                    b.Property<decimal>("ExpectedPool")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("expected_pool");

                    b.Property<int>("ExpenseCycleId")
                        .HasColumnType("integer")
                        .HasColumnName("expense_cycle_id");

                    b.Property<bool>("PayoutConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("payout_confirmed");

                    b.Property<DateTime?>("PayoutConfirmedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("payout_confirmed_at");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_user_id");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer")
                        .HasColumnName("round_number");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_mukando_rounds");

                    b.HasIndex("RecipientUserId")
                        .HasDatabaseName("ix_mukando_rounds_recipient_user_id");

                    b.HasIndex("ExpenseCycleId", "RoundNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_mukando_rounds_expense_cycle_id_round_number");

                    b.ToTable("MukandoRounds", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.MukandoRoundActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("details");

                    b.Property<int>("MukandoRoundId")
                        .HasColumnType("integer")
                        .HasColumnName("mukando_round_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_mukando_round_activities");

                    b.HasIndex("MukandoRoundId")
                        .HasDatabaseName("ix_mukando_round_activities_mukando_round_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mukando_round_activities_user_id");

                    b.ToTable("MukandoRoundActivities", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.MukandoSwapRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpenseCycleId")
                        .HasColumnType("integer")
                        .HasColumnName("expense_cycle_id");

                    b.Property<int>("RequesterRoundId")
                        .HasColumnType("integer")
                        .HasColumnName("requester_round_id");

                    b.Property<int>("RequesterUserId")
                        .HasColumnType("integer")
                        .HasColumnName("requester_user_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("responded_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TargetRoundId")
                        .HasColumnType("integer")
                        .HasColumnName("target_round_id");

                    b.Property<int>("TargetUserId")
                        .HasColumnType("integer")
                        .HasColumnName("target_user_id");

                    b.HasKey("Id")
                        .HasName("pk_mukando_swap_requests");

                    b.HasIndex("ExpenseCycleId")
                        .HasDatabaseName("ix_mukando_swap_requests_expense_cycle_id");

                    b.HasIndex("RequesterRoundId")
                        .HasDatabaseName("ix_mukando_swap_requests_requester_round_id");

                    b.HasIndex("RequesterUserId")
                        .HasDatabaseName("ix_mukando_swap_requests_requester_user_id");

                    b.HasIndex("TargetRoundId")
                        .HasDatabaseName("ix_mukando_swap_requests_target_round_id");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_mukando_swap_requests_target_user_id");

                    b.ToTable("MukandoSwapRequests", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeepLinkUrl")
                        .HasColumnType("text")
                        .HasColumnName("deep_link_url");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("integer")
                        .HasColumnName("related_entity_id");

                    b.Property<bool>("SentViaPush")
                        .HasColumnType("boolean")
                        .HasColumnName("sent_via_push");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.NotificationTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsAdminControlled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin_controlled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_notification_types");

                    b.ToTable("NotificationTypes", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("used_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int?>("UserId1")
                        .HasColumnType("integer")
                        .HasColumnName("user_id1");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_password_reset_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_tokens_user_id");

                    b.HasIndex("UserId1")
                        .HasDatabaseName("ix_password_reset_tokens_user_id1");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpenseCycleId")
                        .HasColumnType("integer")
                        .HasColumnName("expense_cycle_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("PayeeId")
                        .HasColumnType("integer")
                        .HasColumnName("payee_id");

                    b.Property<int>("PayerId")
                        .HasColumnType("integer")
                        .HasColumnName("payer_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("ExpenseCycleId")
                        .HasDatabaseName("ix_payments_expense_cycle_id");

                    b.HasIndex("PayeeId")
                        .HasDatabaseName("ix_payments_payee_id");

                    b.HasIndex("PayerId")
                        .HasDatabaseName("ix_payments_payer_id");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.PushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("p256dh");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_push_subscriptions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_push_subscriptions_user_id");

                    b.ToTable("PushSubscriptions", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackupCodesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("backup_codes_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<bool>("IsMfaEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mfa_enabled");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("MfaEnabledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("mfa_enabled_at");

                    b.Property<string>("MfaSecret")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mfa_secret");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("PasswordLastChanged")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("password_last_changed");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.UserDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppVersion")
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceManufacturer")
                        .HasColumnType("text")
                        .HasColumnName("device_manufacturer");

                    b.Property<string>("DeviceModel")
                        .HasColumnType("text")
                        .HasColumnName("device_model");

                    b.Property<int>("DeviceType")
                        .HasColumnType("integer")
                        .HasColumnName("device_type");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<int>("InstallStatus")
                        .HasColumnType("integer")
                        .HasColumnName("install_status");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTime?>("NextPromptAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("next_prompt_at");

                    b.Property<string>("OsVersion")
                        .HasColumnType("text")
                        .HasColumnName("os_version");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_devices");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_devices_user_id");

                    b.ToTable("UserDevices", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.UserNotificationPreference", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("notification_type_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.HasKey("UserId", "NotificationTypeId")
                        .HasName("pk_user_notification_preferences");

                    b.HasIndex("NotificationTypeId")
                        .HasDatabaseName("ix_user_notification_preferences_notification_type_id");

                    b.ToTable("UserNotificationPreferences", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.WebAuthnCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aaguid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aaguid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("credential_id");

                    b.Property<string>("DeviceFriendlyName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_friendly_name");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_key");

                    b.Property<long>("SignCount")
                        .HasColumnType("bigint")
                        .HasColumnName("sign_count");

                    b.Property<int?>("UserDeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("user_device_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("UserId1")
                        .HasColumnType("integer")
                        .HasColumnName("user_id1");

                    b.HasKey("Id")
                        .HasName("pk_web_authn_credentials");

                    b.HasIndex("UserDeviceId")
                        .HasDatabaseName("ix_web_authn_credentials_user_device_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_web_authn_credentials_user_id");

                    b.HasIndex("UserId1")
                        .HasDatabaseName("ix_web_authn_credentials_user_id1");

                    b.ToTable("WebAuthnCredentials", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.CycleMember", b =>
                {
                    b.HasOne("Batanai.Api.Models.ExpenseCycle", null)
                        .WithMany()
                        .HasForeignKey("ExpenseCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cycle_members_expense_cycles_expense_cycle_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cycle_members_users_user_id");
                });

            modelBuilder.Entity("Batanai.Api.Models.EmailVerificationToken", b =>
                {
                    b.HasOne("Batanai.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_verification_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Batanai.Api.Models.Expense", b =>
                {
                    b.HasOne("Batanai.Api.Models.ExpenseCycle", null)
                        .WithMany()
                        .HasForeignKey("ExpenseCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_expense_cycles_expense_cycle_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("LoggedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_users_logged_by_user_id");
                });

            modelBuilder.Entity("Batanai.Api.Models.ExpenseCycle", b =>
                {
                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expense_cycles_users_created_by_user_id");

                    b.HasOne("Batanai.Api.Models.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expense_cycles_currencies_currency_id");

                    b.HasOne("Batanai.Api.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expense_cycles_groups_group_id");
                });

            modelBuilder.Entity("Batanai.Api.Models.ExpenseDispute", b =>
                {
                    b.HasOne("Batanai.Api.Models.Expense", null)
                        .WithMany()
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expense_disputes_expenses_expense_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("RaisedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expense_disputes_users_raised_by_user_id");
                });

            modelBuilder.Entity("Batanai.Api.Models.FeatureBugReport", b =>
                {
                    b.HasOne("Batanai.Api.Models.User", "SubmittedByUser")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feature_bug_reports_users_submitted_by_user_id");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("Batanai.Api.Models.FeatureBugReportCategory", b =>
                {
                    b.HasOne("Batanai.Api.Models.FeatureBugReport", "Report")
                        .WithMany("Categories")
                        .HasForeignKey("FeatureBugReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feature_bug_report_categories_feature_bug_reports_feature_bug_re");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Batanai.Api.Models.Group", b =>
                {
                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_groups_users_created_by_user_id");
                });

            modelBuilder.Entity("Batanai.Api.Models.GroupMember", b =>
                {
                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_group_members_users_approved_by_user_id");

                    b.HasOne("Batanai.Api.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_groups_group_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_group_members_users_invited_by_user_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_users_user_id");
                });

            modelBuilder.Entity("Batanai.Api.Models.MemberObligation", b =>
                {
                    b.HasOne("Batanai.Api.Models.Expense", null)
                        .WithMany()
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_obligations_expenses_expense_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_obligations_users_user_id");
                });

            modelBuilder.Entity("Batanai.Api.Models.MukandoContribution", b =>
                {
                    b.HasOne("Batanai.Api.Models.MukandoRound", null)
                        .WithMany()
                        .HasForeignKey("MukandoRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mukando_contributions_mukando_rounds_mukando_round_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mukando_contributions_users_user_id");
                });

            modelBuilder.Entity("Batanai.Api.Models.MukandoOptOutRequest", b =>
                {
                    b.HasOne("Batanai.Api.Models.ExpenseCycle", null)
                        .WithMany()
                        .HasForeignKey("ExpenseCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mukando_opt_out_requests_expense_cycles_expense_cycle_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("RespondedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_mukando_opt_out_requests_users_responded_by_user_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mukando_opt_out_requests_users_user_id");
                });

            modelBuilder.Entity("Batanai.Api.Models.MukandoPayout", b =>
                {
                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ConfirmedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mukando_payouts_users_confirmed_by_user_id");

                    b.HasOne("Batanai.Api.Models.MukandoRound", null)
                        .WithMany()
                        .HasForeignKey("MukandoRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mukando_payouts_mukando_rounds_mukando_round_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mukando_payouts_users_recipient_user_id");
                });

            modelBuilder.Entity("Batanai.Api.Models.MukandoRound", b =>
                {
                    b.HasOne("Batanai.Api.Models.ExpenseCycle", null)
                        .WithMany()
                        .HasForeignKey("ExpenseCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mukando_rounds_expense_cycles_expense_cycle_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mukando_rounds_users_recipient_user_id");
                });

            modelBuilder.Entity("Batanai.Api.Models.MukandoRoundActivity", b =>
                {
                    b.HasOne("Batanai.Api.Models.MukandoRound", null)
                        .WithMany()
                        .HasForeignKey("MukandoRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mukando_round_activities_mukando_rounds_mukando_round_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mukando_round_activities_users_user_id");
                });

            modelBuilder.Entity("Batanai.Api.Models.MukandoSwapRequest", b =>
                {
                    b.HasOne("Batanai.Api.Models.ExpenseCycle", null)
                        .WithMany()
                        .HasForeignKey("ExpenseCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mukando_swap_requests_expense_cycles_expense_cycle_id");

                    b.HasOne("Batanai.Api.Models.MukandoRound", null)
                        .WithMany()
                        .HasForeignKey("RequesterRoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mukando_swap_requests_mukando_rounds_requester_round_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mukando_swap_requests_users_requester_user_id");

                    b.HasOne("Batanai.Api.Models.MukandoRound", null)
                        .WithMany()
                        .HasForeignKey("TargetRoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mukando_swap_requests_mukando_rounds_target_round_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mukando_swap_requests_users_target_user_id");
                });

            modelBuilder.Entity("Batanai.Api.Models.Notification", b =>
                {
                    b.HasOne("Batanai.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Batanai.Api.Models.PasswordResetToken", b =>
                {
                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_users_user_id");

                    b.HasOne("Batanai.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .HasConstraintName("fk_password_reset_tokens_users_user_id1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Batanai.Api.Models.Payment", b =>
                {
                    b.HasOne("Batanai.Api.Models.ExpenseCycle", null)
                        .WithMany()
                        .HasForeignKey("ExpenseCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_expense_cycles_expense_cycle_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("PayeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_users_payee_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_users_payer_id");
                });

            modelBuilder.Entity("Batanai.Api.Models.PushSubscription", b =>
                {
                    b.HasOne("Batanai.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_push_subscriptions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Batanai.Api.Models.UserDevice", b =>
                {
                    b.HasOne("Batanai.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_devices_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Batanai.Api.Models.UserNotificationPreference", b =>
                {
                    b.HasOne("Batanai.Api.Models.NotificationTypeEntity", "NotificationType")
                        .WithMany()
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_notification_preferences_notification_types_notification_");

                    b.HasOne("Batanai.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_notification_preferences_users_user_id");

                    b.Navigation("NotificationType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Batanai.Api.Models.WebAuthnCredential", b =>
                {
                    b.HasOne("Batanai.Api.Models.UserDevice", "UserDevice")
                        .WithMany()
                        .HasForeignKey("UserDeviceId")
                        .HasConstraintName("fk_web_authn_credentials_user_devices_user_device_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_web_authn_credentials_users_user_id");

                    b.HasOne("Batanai.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_web_authn_credentials_users_user_id1");

                    b.Navigation("User");

                    b.Navigation("UserDevice");
                });

            modelBuilder.Entity("Batanai.Api.Models.FeatureBugReport", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
