// <auto-generated />
using System;
using Batanai.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Batanai.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260403042104_AddGroupsFeature")]
    partial class AddGroupsFeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Batanai.Api.Models.AppConfigEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("data_type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read_only");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean")
                        .HasColumnName("is_secret");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<bool>("RequiresRestart")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_restart");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_app_config_entries");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_app_config_entries_key");

                    b.ToTable("AppConfigEntries", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.CycleMember", b =>
                {
                    b.Property<int>("ExpenseCycleId")
                        .HasColumnType("integer")
                        .HasColumnName("expense_cycle_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_at");

                    b.HasKey("ExpenseCycleId", "UserId")
                        .HasName("pk_cycle_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_cycle_members_user_id");

                    b.ToTable("CycleMembers", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.EmailVerificationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("used_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int?>("UserId1")
                        .HasColumnType("integer")
                        .HasColumnName("user_id1");

                    b.HasKey("Id")
                        .HasName("pk_email_verification_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_email_verification_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_email_verification_tokens_user_id");

                    b.HasIndex("UserId1")
                        .HasDatabaseName("ix_email_verification_tokens_user_id1");

                    b.ToTable("EmailVerificationTokens", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpenseCycleId")
                        .HasColumnType("integer")
                        .HasColumnName("expense_cycle_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("PaidByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("paid_by_user_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_expenses");

                    b.HasIndex("ExpenseCycleId")
                        .HasDatabaseName("ix_expenses_expense_cycle_id");

                    b.HasIndex("PaidByUserId")
                        .HasDatabaseName("ix_expenses_paid_by_user_id");

                    b.ToTable("Expenses", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.ExpenseCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_expense_cycles");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_expense_cycles_created_by_user_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_expense_cycles_group_id");

                    b.ToTable("ExpenseCycles", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_groups_created_by_user_id");

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.GroupMember", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("GroupRole")
                        .HasColumnType("integer")
                        .HasColumnName("group_role");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("invited_at");

                    b.Property<int>("InvitedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("invited_by_user_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("responded_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("GroupId", "UserId")
                        .HasName("pk_group_members");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("ix_group_members_invited_by_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_group_members_user_id");

                    b.ToTable("GroupMembers", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.MemberObligation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountOwed")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_owed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpenseId")
                        .HasColumnType("integer")
                        .HasColumnName("expense_id");

                    b.Property<bool>("IsSettled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_settled");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("settled_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_member_obligations");

                    b.HasIndex("ExpenseId")
                        .HasDatabaseName("ix_member_obligations_expense_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_member_obligations_user_id");

                    b.ToTable("MemberObligations", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeepLinkUrl")
                        .HasColumnType("text")
                        .HasColumnName("deep_link_url");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("integer")
                        .HasColumnName("related_entity_id");

                    b.Property<bool>("SentViaPush")
                        .HasColumnType("boolean")
                        .HasColumnName("sent_via_push");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.NotificationTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsAdminControlled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin_controlled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_notification_types");

                    b.ToTable("NotificationTypes", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("used_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int?>("UserId1")
                        .HasColumnType("integer")
                        .HasColumnName("user_id1");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_password_reset_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_tokens_user_id");

                    b.HasIndex("UserId1")
                        .HasDatabaseName("ix_password_reset_tokens_user_id1");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExpenseCycleId")
                        .HasColumnType("integer")
                        .HasColumnName("expense_cycle_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("PayeeId")
                        .HasColumnType("integer")
                        .HasColumnName("payee_id");

                    b.Property<int>("PayerId")
                        .HasColumnType("integer")
                        .HasColumnName("payer_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("ExpenseCycleId")
                        .HasDatabaseName("ix_payments_expense_cycle_id");

                    b.HasIndex("PayeeId")
                        .HasDatabaseName("ix_payments_payee_id");

                    b.HasIndex("PayerId")
                        .HasDatabaseName("ix_payments_payer_id");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.PushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("p256dh");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_push_subscriptions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_push_subscriptions_user_id");

                    b.ToTable("PushSubscriptions", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackupCodesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("backup_codes_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<bool>("IsMfaEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mfa_enabled");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("MfaEnabledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("mfa_enabled_at");

                    b.Property<string>("MfaSecret")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mfa_secret");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("PasswordLastChanged")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("password_last_changed");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.UserDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppVersion")
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceManufacturer")
                        .HasColumnType("text")
                        .HasColumnName("device_manufacturer");

                    b.Property<string>("DeviceModel")
                        .HasColumnType("text")
                        .HasColumnName("device_model");

                    b.Property<int>("DeviceType")
                        .HasColumnType("integer")
                        .HasColumnName("device_type");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<int>("InstallStatus")
                        .HasColumnType("integer")
                        .HasColumnName("install_status");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTime?>("NextPromptAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("next_prompt_at");

                    b.Property<string>("OsVersion")
                        .HasColumnType("text")
                        .HasColumnName("os_version");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_devices");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_devices_user_id");

                    b.ToTable("UserDevices", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.UserNotificationPreference", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("notification_type_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.HasKey("UserId", "NotificationTypeId")
                        .HasName("pk_user_notification_preferences");

                    b.HasIndex("NotificationTypeId")
                        .HasDatabaseName("ix_user_notification_preferences_notification_type_id");

                    b.ToTable("UserNotificationPreferences", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.WebAuthnCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aaguid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aaguid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("credential_id");

                    b.Property<string>("DeviceFriendlyName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_friendly_name");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_key");

                    b.Property<long>("SignCount")
                        .HasColumnType("bigint")
                        .HasColumnName("sign_count");

                    b.Property<int?>("UserDeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("user_device_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("UserId1")
                        .HasColumnType("integer")
                        .HasColumnName("user_id1");

                    b.HasKey("Id")
                        .HasName("pk_web_authn_credentials");

                    b.HasIndex("UserDeviceId")
                        .HasDatabaseName("ix_web_authn_credentials_user_device_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_web_authn_credentials_user_id");

                    b.HasIndex("UserId1")
                        .HasDatabaseName("ix_web_authn_credentials_user_id1");

                    b.ToTable("WebAuthnCredentials", (string)null);
                });

            modelBuilder.Entity("Batanai.Api.Models.CycleMember", b =>
                {
                    b.HasOne("Batanai.Api.Models.ExpenseCycle", null)
                        .WithMany()
                        .HasForeignKey("ExpenseCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cycle_members_expense_cycles_expense_cycle_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cycle_members_users_user_id");
                });

            modelBuilder.Entity("Batanai.Api.Models.EmailVerificationToken", b =>
                {
                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_verification_tokens_users_user_id");

                    b.HasOne("Batanai.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .HasConstraintName("fk_email_verification_tokens_users_user_id1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Batanai.Api.Models.Expense", b =>
                {
                    b.HasOne("Batanai.Api.Models.ExpenseCycle", null)
                        .WithMany()
                        .HasForeignKey("ExpenseCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_expense_cycles_expense_cycle_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("PaidByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_users_paid_by_user_id");
                });

            modelBuilder.Entity("Batanai.Api.Models.ExpenseCycle", b =>
                {
                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expense_cycles_users_created_by_user_id");

                    b.HasOne("Batanai.Api.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_expense_cycles_groups_group_id");
                });

            modelBuilder.Entity("Batanai.Api.Models.Group", b =>
                {
                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_groups_users_created_by_user_id");
                });

            modelBuilder.Entity("Batanai.Api.Models.GroupMember", b =>
                {
                    b.HasOne("Batanai.Api.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_groups_group_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_users_invited_by_user_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_users_user_id");
                });

            modelBuilder.Entity("Batanai.Api.Models.MemberObligation", b =>
                {
                    b.HasOne("Batanai.Api.Models.Expense", null)
                        .WithMany()
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_obligations_expenses_expense_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_obligations_users_user_id");
                });

            modelBuilder.Entity("Batanai.Api.Models.Notification", b =>
                {
                    b.HasOne("Batanai.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Batanai.Api.Models.PasswordResetToken", b =>
                {
                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_users_user_id");

                    b.HasOne("Batanai.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .HasConstraintName("fk_password_reset_tokens_users_user_id1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Batanai.Api.Models.Payment", b =>
                {
                    b.HasOne("Batanai.Api.Models.ExpenseCycle", null)
                        .WithMany()
                        .HasForeignKey("ExpenseCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_expense_cycles_expense_cycle_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("PayeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_users_payee_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_users_payer_id");
                });

            modelBuilder.Entity("Batanai.Api.Models.PushSubscription", b =>
                {
                    b.HasOne("Batanai.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_push_subscriptions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Batanai.Api.Models.UserDevice", b =>
                {
                    b.HasOne("Batanai.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_devices_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Batanai.Api.Models.UserNotificationPreference", b =>
                {
                    b.HasOne("Batanai.Api.Models.NotificationTypeEntity", "NotificationType")
                        .WithMany()
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_notification_preferences_notification_types_notification_");

                    b.HasOne("Batanai.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_notification_preferences_users_user_id");

                    b.Navigation("NotificationType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Batanai.Api.Models.WebAuthnCredential", b =>
                {
                    b.HasOne("Batanai.Api.Models.UserDevice", "UserDevice")
                        .WithMany()
                        .HasForeignKey("UserDeviceId")
                        .HasConstraintName("fk_web_authn_credentials_user_devices_user_device_id");

                    b.HasOne("Batanai.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_web_authn_credentials_users_user_id");

                    b.HasOne("Batanai.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_web_authn_credentials_users_user_id1");

                    b.Navigation("User");

                    b.Navigation("UserDevice");
                });
#pragma warning restore 612, 618
        }
    }
}
